sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- ./build.sh
# test image
#- docker run -it thenatureofsoftware/traefik-arm64 version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep VERSION Dockerfile|awk 'NF>1{print $NF'})
    docker tag thenatureofsoftware/traefik-arm64 thenatureofsoftware/traefik-arm64:$TAG
    docker push thenatureofsoftware/traefik-arm64:$TAG
    docker push thenatureofsoftware/traefik-arm64:latest
  fi
